# Generated by Django 3.2.25 on 2024-05-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, help_text='예약 확정 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('exam_slot', models.ForeignKey(help_text='예약된 시험 슬롯', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='exams.examslot')),
            ],
        ),
    ]
