# Generated by Django 3.2.25 on 2024-05-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='시험 제목', max_length=255)),
                ('description', models.CharField(help_text='시험 설명', max_length=255)),
                ('duration', models.IntegerField(default=2, help_text='시험 진행 시간(hour)')),
                ('start_time', models.DateTimeField(db_index=True, help_text='시험 시작 시간')),
                ('reservation_count', models.IntegerField(default=0, help_text='예약 카운트')),
                ('capacity', models.IntegerField(default=50000, help_text='최대 수용 인원(명)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
