# Generated by Django 3.2.25 on 2024-05-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_exam_slot_reservation_exam'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamSlot',
            new_name='Exam',
        ),
    ]
